using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RelativeDatabase : MonoBehaviour
{
    public List<Relative> relativeList = new List<Relative>();
    
    // Start is called before the first frame update
    void Start()
    {
        relativeList.Add(new Relative("Dorothy", 0, 67, "This is you!", "You are one stone cold fox."));
        relativeList.Add(new Relative("Eugene", 1, 82, "Husband", "A simple man with simple sensibilities. His bank account was simply loaded when you met him. There was genuine love there, too, to be sure. He was kind and sincere. He took you to the opera and lavished you with gifts. He gave you your children (although, that’s also in the “cons list”, if you’re being honest). Time took its toll and the two of you became more distant. Eugene needed you to raise the children, so that he could attend to matters of business (his mistress). You can’t quite decide whether or not you hate him for that, but then again, it isn’t really clear who cheated on whom first. He’s an idiot, to be sure. And his methods of handling business are morally reprehensible, but he leaves you to do what you like nowadays, and you’ve found you like the freedom."));
        relativeList.Add(new Relative("Rhonda", 2, 39, "Firstborn Child", "Whipsmart and a royal pain-in-your-ass, Rhonda has perfected the art of conning you out of your own money. You resent her for her callousness, but you can’t deny a level of pride in how devious and intelligent she is - surely she learned that from you. She has exquisite taste when it comes to fashion and art, but her taste in lovers is… lacking. She has a predilection for dodgy women, but never dates them for more than a couple of weeks at a time . She broke things off with the one woman you liked - a brilliant art curator - as soon as she realized you approved. Despite her conniving, spiteful nature, the press is enamored of her. She’s got them wrapped around her little finger. The only people who don’t like Rhonda are her siblings, and the feeling is fairly mutual."));
        relativeList.Add(new Relative("Phillip", 3, 32, "Adopted Child", "Sweet, carefree Phillip. He’d be the apple-of-your-eye, if only there was a brain in that giant, empty head of his. He’s the activist in the family, so to speak. He pours all of his money into charities, non-profits and politics. The only problem is that he doesn’t understand a thing about their causes. He once spoke at two seperate rallies for dramatically opposed causes in the same week and had no idea. He’s a yes-man with a heart of gold, but his ignorance often does more ill than good - both to your family’s reputation, and to the infinite foundations he attempts to support. You can’t count how many times you’ve started a sentence with, “Oh honey…” while speaking to him. He’s become a bit of a joke in the press, but luckily, his puppy-dog brain has kept him from noticing."));
        relativeList.Add(new Relative("Joff", 4, 29, "Second-born Child", "The doctor’s swear he’s yours, but you’re still not certain you believe them. The perpetual teenager, Joff is moody and angry all the time, insisting that no one understands him. To be fair, no one does. He spends far too much time locked in one of his three bedrooms surfing the web and listening to s horrible racket he calls “music”. His one redeeming quality is that during all that time spent hiding away he learned cyber hacking. He’s managed to find very incriminating evidence on some very important people when you’ve needed him to, and that proved to be invaluable for you in a couple of dire situations. There is something about him that’s a bit unsettling, however. Perhaps it was the mysterious way in which his pet rats died? Or perhaps it’s just that dead-eyed, shark-like stare of his..."));
        relativeList.Add(new Relative("Sasha", 5, 22, "Youngest Child", "Sasha is the intellectual type, in a manner of speaking. She’s a perpetual student whose life’s purpose seems to be to obtain as many useless degrees as possible and to drain the family fortune by attending unimaginably expensive liberal arts colleges. She has degrees in Citrus, Blacksmithing, Floral Management, Mortuary Science, and Puppet Arts (yes, those are all real degrees). She’s happy to correct you wherever possible and will go on at length talking about obscure facts you never needed to know. Despite being rather annoying at times, you have to give her credit - she is probably the most “normal” in the family. She may be unemployable, but she is at least a decent human being with somewhat good intentions. Of course, you did have to payoff a school official or two in order to get her into a couple of those universities."));
        relativeList.Add(new Relative("Puddles", 6, 9, "Family Dog", "He’s a good boy! Yes he is! He has two separate nannies, but he needs all the attention he can get. His medical issues have made him fairly high maintenance. There was that one time he peed on your designer gown just before the Met Gala in 2016, of course. And that time that he licked his butthole in front of the paparazzi - the tabloids were merciless. He’s also become pretty gassy in his old age, and frankly, he’s only slightly more intelligent than Phillip. Still, you do love that squishy face and the way his whole body is like one tubby, little sausage."));
    }
}
